### ISSUE TITLE
Swagger UI for for spec'ed functions during mount

### ISSUE THREAD

**Issue by viesti** [cgrand/portkey#18]
With say spec-tools https://github.com/metosin/spec-tools/blob/master/src/spec_tools/swagger/core.cljc and host swagger-ui in S3 (have to "mount" it too).

**Comment by cgrand** [comment]
I don't know if pushing more swagger in is a good thing. I understand it's an expedient to reach the goal of having a test UI "for free" but in the long term?

**Comment by viesti** [comment]
Ah true, the actual goal is a test UI, not necessarily swagger-ui :)

**Comment by viesti** [comment]
Closing this now for better statement of the actual need.
